user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


stream {
    
    log_format kafka_proxy '$remote_addr [$time_local] '
                           'protocol=$protocol status=$status '
                           'bytes_sent=$bytes_sent bytes_received=$bytes_received '
                           'session_time=$session_time '
                           'sni="$ssl_preread_server_name" '
                           'upstream="$upstream_addr"';

    # Enable the log file
    access_log /var/log/nginx/kafka_access.log kafka_proxy;

    server {
        listen 4431;
        proxy_pass broker_1_backend;
        proxy_timeout 1h;
        proxy_connect_timeout 5s;
    }

    server {
        listen 4432;
        proxy_pass broker_2_backend;
        proxy_timeout 1h;
        proxy_connect_timeout 5s;
    }

    server {
        listen 4433;
        proxy_pass broker_3_backend;
        proxy_timeout 1h;
        proxy_connect_timeout 5s;
    }

    # 2. Bootstrap Port (Optional)
    # External Port 443 -> Round Robin across all brokers
    server {
        listen 443;
        proxy_pass kafka_bootstrap;
    }

    # Upstream Definitions
    upstream broker_1_backend {
        server ip-10-0-10-1.ap-south-1.compute.internal:4431;
    }

    upstream broker_2_backend {
        server ip-10-0-10-2.ap-south-1.compute.internal:4432;
    }

    upstream broker_3_backend {
        server ip-10-0-10-3.ap-south-1.compute.internal:4433;
    }

    upstream kafka_bootstrap {
        server ip-10-0-10-1.ap-south-1.compute.internal:4431;
        server ip-10-0-10-2.ap-south-1.compute.internal:4432;
        server ip-10-0-10-3.ap-south-1.compute.internal:4433;
    }
}
