user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


stream {
    # Map the SNI hostname to a specific upstream group
    map $ssl_preread_server_name $kafka_backend {
        broker1.sahil.se.net  broker_1;
        broker2.sahil.se.net  broker_2;
        broker3.sahil.se.net  broker_3;
        default              kafka_bootstrap;
    }

    upstream broker_1 {
        server ip-10-0-13-91.ap-south-1.compute.internal:9091;
    }

    upstream broker_2 {
        server ip-10-0-13-92.ap-south-1.compute.internal:9091;
    }

    upstream broker_3 {
        server ip-10-0-13-93.ap-south-1.compute.internal:9091;
    }

    upstream kafka_bootstrap {
        # Round-robin for initial connection
        server ip-10-0-13-91.ap-south-1.compute.internal:9091;
        server ip-10-0-13-92.ap-south-1.compute.internal:9091;
        server ip-10-0-13-93.ap-south-1.compute.internal:9091;
    }

    server {
        listen 443; # External Port
        proxy_pass $kafka_backend;
        ssl_preread on; # This is the magic that reads the SNI
    }
}
